### ISSUE TITLE
Add User schema

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sing_for_needs#128]
## Expected Behavior

Create a users schema within an Accounts context. The user should have the following fields

- username
- password
- password confirmation
- Password Hash
- email

## Current Behavior

User schema hasnt been added to the repo
## Possible Solution

`mix phx.gen.context Accounts User users username:string `

**Comment by jackline-kaunda** [comment]
Hey at mike aone, could I pick up this issue?

**Comment by aonomike** [comment]
Hi @misswayua I already started work on the issue...I will be creating a PR shortly...we can plan a pairing session tomorrow or wherever you are free to complete the work on it...you can also let me know if you find another issue you want to take lead on...thanks
