### ISSUE TITLE
Add credo

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sing_for_needs#13]
Add credo

You'll want to add:
`  - mix credo`
to the travis scripts.

**Comment by wevtimoteo** [comment]
@mattwr18 and me can push this one in next pairing session on next monday using [EbertApp](https://docs.ebertapp.io/engines/credo/)

**Comment by FedericoEsparza** [comment]
@wevtimoteo Sounds good! That'd be great. cc: @mattwr18
