### ISSUE TITLE
Add Artists resource

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sing_for_needs#14]

**Comment by mattwr18** [comment]
Could you please add more information about this issue @FedericoEsparza, we would like to work on this next week...

**Comment by FedericoEsparza** [comment]
@mattwr18 Yep. Will do. I still haven’t decided on the architecture of the Contexts, but I’ll do that by next week.

**Comment by mattwr18** [comment]
thanks :wink: we'll have our regular pairing session on Thursday next week, cause it's my wife's bday on Monday

**Comment by FedericoEsparza** [comment]
@wevtimoteo @mattwr18 Ok. You guys are pros, so I won't give you too much guidance:

Run this generator command: 
```
mix phx.gen.json ArtistDirectory Artist artists name:string user_id:references:users
```
`ArtistDirectory` is the context. `Artist` is the schema (resource), `artists` is the database name.
<img width="491" alt="screenshot 2019-03-07 15 38 49" src="https://user-images.githubusercontent.com/11988089/53991004-7db12b80-4121-11e9-8e2e-66f07fbe5449.png">

Let's keep the fields simple for now.

Follow the instructions about adding it to the `/api` route scope and running the migrations.

You should run into issues when trying to run the migration, because we haven't set up ecto on the backend, yet.

I followed Dave Thomas' advice of not adding it when you don't need it, yet `(mix phx.new sing_for_needs --no-ecto)`
 
Now we need it, so you'll have to research how to add it. 

But if you follow most of the instructions in this section of the ecto docs, and look at your Problems in VSCode, you should be able to figure it out: https://hexdocs.pm/ecto/getting-started.html#adding-ecto-to-an-application

**Comment by mattwr18** [comment]
great! thanks @FedericoEsparza, not sure if we'll get to it today

**Comment by yakryder** [comment]
Can we failing acceptance test this? I'm hoping I can make it in tomorrow

Also hoping the `tests` label here means this is meant to be test-driven

**Comment by FedericoEsparza** [comment]
@SherSpock does not mean `test-driven`. I'll create a `tdd` label to make the distinction. The generator will create tests.

The ticket is sure to be `error-driven`, if that's any consolation, because, as I mentioned, it was set up without Ecto.

The generator will also output additional instructions about the migration and the api.

Since we will have more resources to add (i.e. `performance`, `cause`, et al.), those can be _integration_ test driven, after there are tests to reference, in the repo, with the `artist` resource.

You're most welcome to work on those, after this one is merged. I can create tickets for those.

Given that this is an API backend, the high-level end-to-end tests will be driven by Cypress, more than likely.

I'm open to be persuaded, otherwise, in terms have having acceptance tests for the API, within the backend, using chromedriver.

I have written tickets with a fair amount of guidance, on our phoenix-only app (`championer_one`), where we did use acceptance tests, in a test-driven fashion. And there's `Mango`, too, of course.

I don't know that acceptance tests work so easily within an API-only backend.

**Comment by yakryder** [comment]
So Matt, Mike, and I had the acceptance test discussion the other day...basically, I see no problem with calling a strictly API-exercising test that if there are (or are meant to be) users interacting with the app at the level of the API.

If users are only interacting with the app through our front-end (as I suspect is meant to be the primary or only supported workflow in this case), then yeah, maybe acceptance test isn't the best name. 

There is some question in my mind whether acceptance test and end-to-end test are fully synonymous, but if we shy away from end-to-end as well in this context it seems unlikely anyone would object to calling tests that exercise the web API either API integration or API workflow tests.

**Comment by FedericoEsparza** [comment]
@SherSpock "API integration" works. I'm not sure how they would be structured or what they buy us beyond what the controller tests that already would test the API.

I'm not convinced that we should recreate the front end in a headless manner, to generate a type of acceptance test for the backend, but I might be convinced otherwise, and I don't know that you were suggesting this.

In terms of end-to-end vs. acceptance tests, I'm envisioning that we'll have a sparingly few 
end-to-end cypress tests that hit the real backend, ran as needed and in CI, maybe just for staging PRs (but they might be ok for develop PRs, too).

We'll have a healthier amount that stub out the backend, which we'll call acceptance tests.

Your further input to help shape the testing architecture is most welcome.

**Feel free to explore an "API integration" testing structure for the backend.**

**Comment by yakryder** [comment]
@FedericoEsparza We wouldn't do controller tests if we were doing API integration tests -- I agree that there isn't much point in doing both.

I'm not suggesting we recreate the front end, no. These tests would use one or more clients to talk to the backend routes. The client(s) and calling test code would ideally be written in JavaScript -- that way client code could be packaged up as an SDK that could be commonly consumed by the API integration tests, the web front-end, and potentially a mobile front-end. The odds of us doing React Native over direct native on the mobile side -- if we were to tackle the mobile side -- seem quite high. 

If we truly anticipate not having any API consumers ever apart from our front-ends, then limiting end to end tests to their respective front-ends doesn't seem crazy.

**Comment by FedericoEsparza** [comment]
@SherSpock Great discussion, Ryder.

I'm intrigued by the idea of an SDK consuming our API integration tests, and **I'd like to hear more about its potential.** And I do fear that it might be time consuming and an extensive effort, so maybe I might be persuaded that it's not.   

While I don't want to squash enthusiasm for API Integration tests and their being used for test-driven development, in the absence of major volunteer engineering resources, **I'm happy with the API controller tests generated by the generator command, as requested in the ticket, even if we throw them out later for some API Integration tests, instead.**

Although, as long as progress is being made, in the right direction, **I'm okay with whatever path the developers want to take.**

I'm glad you brought up React Native, because we haven't focused on mobile at all. And I do agree that we'd be much more likely to go with it, over native (with Swift *or Java/Kotlin).* **For mobile end-to-end testing, as a result of going with React Native, we'd use Detox.**

**Comment by yakryder** [comment]
🎉
