### ISSUE TITLE
Address npm vulnerabilities

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sing_for_needs#15]
Remove vulnerabilities

When we run `cd assets && npm audit` we get 790 vulnerabilities

<img width="837" alt="screenshot 2019-02-25 15 04 17" src="https://user-images.githubusercontent.com/11988089/53368625-2b158980-3941-11e9-965a-db196d78eade.png">

To fix, make sure that you're in the `/assets` folder.
Install `npm-check-updates` globally by running: 
```
npm install -g npm-check-updates
```

Update the `package.json` file by running: 
```
ncu -a
```
Update the `package-lock.json` file by runinng:
```
npm install
``` 

Rerun `npm audit` to make sure the vulnerabilities are gone.

**Comment by yakryder** [comment]
Is this project running in production, do we have comprehensive test coverage, and/or do we have A/B testing or any incremental roll-out strategy?

Trying to decide if this is actually easy and low-risk and, if so, whether to leave this for somebody

**Comment by FedericoEsparza** [comment]
@SherSpock Not running in production, yet. Joseph and Linda are planning to get the staging and production environments set up on GCP.

No to the remaining conditional question.

It is a low-risk, complete node module dependency upgrade, at this point, since the backend is freshly out of hibernation, and was practically a phx 1.3 new project before going into hibernation. It's been upgraded to 1.4 and has had some environment and CI configuration work done, but that's about it.

**Comment by yakryder** [comment]
Gotcha. This is primo low-hanging fruit then -- will leave it be in hopes an AV/JS newcomer will want to pick it up

**Comment by yakryder** [comment]
Either close #9 as duplicate between now and when this work closes, or close #9 when this closes
