### ISSUE TITLE
Discuss: Pin all the versions

### ISSUE THREAD

**Issue by yakryder** [AgileVentures/sing_for_needs#20]
Don't want to be the guy who just submits a PR with a big change without talking it over first.

Pinning the versions of all project dependencies is a habit I picked up from Elm. A chunk of this could be done in tandem with #15.

Thoughts?

**Comment by FedericoEsparza** [comment]
@SherSpock I agree. Let's pin the versions using the `~` tilde operator (e.g. `"~1.2.3"`). I still like the security patches to get in, but the caret operator `^`  is a bit too liberal, and only pins to the major semantic version.

It can be done independently of #15 (meaning, before or after).

Go for it!

Thanks for bringing it up.

**Comment by yakryder** [comment]
Sounds great

**Comment by yakryder** [comment]
This was just an input-gathering ticket. Implementation ticket is #37.

If you disagree with the proposed solution, please share your thoughts. There is still time for this issue to be reopened and the implementation ticket changed.

**Comment by FedericoEsparza** [comment]
@SherSpock Thanks for updating the tickets and cleaning up the board, Ryder!

**Comment by yakryder** [comment]
@FedericoEsparza Absolutely
