### ISSUE TITLE
Move issues from waffle Board

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sing_for_needs#21]
Waffle is closing in 2 months. It would be nice to migrate the issue tracker to [zenhub](https://app.zenhub.com/)?

**Comment by FedericoEsparza** [comment]
@aonomike Good work, helping out on this ticket. Zenhub will actually be a backup or alternative to our JIRA board, but I'm a bit behind on getting it configured.

I'll go ahead and close this ticket.
