### ISSUE TITLE
Update README for issue tracker link

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sing_for_needs#22]
Update the README to state clearly that our board has been migrated to [Zenhub](https://app.zenhub.com/workspaces/sing-for-needs-5c8d188a534a9b0a86cdc451/boards?repos=108547295) from [waffle](https://waffle.io/AgileVentures/sing_for_needs)

**Comment by FedericoEsparza** [comment]
@aonomike pointed out, during the Elixir Mob, that I inadvertently took care of this, already, with PR #35 

Sorry if you had started to work on it, Mike.
