### ISSUE TITLE
Error loading module telemetry

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/sing_for_needs#31]
I have been facing an issue running the tests, or trying to run the migrations after having added ecto. It's giving this output

```
mix ecto.migrate                                                                          
[error] Loading of /home/mattwr18/elixir/sing_for_needs/_build/dev/lib/telemetry/ebin/telemetry.beam failed: :badfile

[error] beam/beam_load.c(1863): Error loading module telemetry:
  This BEAM file was compiled for a later version of the run-time system than 20.
  To fix this, please recompile this module with an 20 compiler.
  (Use of opcode 160; this emulator supports only up to 159.)
```

I have spent a half an hour to an hour searching the internet and I feel like I have a good idea what the issue is... I have used Erlang 21 before and it seems I need to recompile telemetry, but I can't seem to get it to work... 

I have tried `mix compile`, `mix compile.erlang`, removing my `_build` directory, tried `asdf local elixir 1.8.1-otp-21`

It is working fine for @aonomike and @75pollet 
I'm on Ubuntu 16.04

any ideas @FedericoEsparza @SherSpock?

**Comment by yakryder** [comment]
Just took a glance at it and haven't encountered before, so grain of salt.

So I'm noticing it looks like you didn't try recompiling or reinstalling Elixir itself, which is one of the remedies mentioned on this link I'm sure you've seen
https://github.com/elixir-lang/elixir/issues/8378

Would be curious if that yields different results

**Comment by mattwr18** [comment]
thanks for responding here @SherSpock... sorry it took so long to respond, I guess it wasn't clear to me how to "recompile Elixir"
what I ended up doing to get passed it was to set my local elixir to `asdf local elixir 1.8.1-otp-21`

First, make sure you have it installed by running `asdf install elixir 1.8.1-otp-21`
