### ISSUE TITLE
Update dependencies to fix deprecation warnings

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/sing_for_needs#32]
It seems that we have upgraded Elixir, but not refactored deprecated code

## Steps to Reproduce:
1. Run `mix compile`

I am getting this output
```
warning: Enum.chunk/2 is deprecated. Use Enum.chunk_every/2 instead
  lib/gettext/po/parser.ex:58

warning: Enum.partition/2 is deprecated. Use Enum.split_with/2 instead
Found at 3 locations:
  lib/gettext/extractor_agent.ex:64
  lib/gettext/po/parser.ex:44
  lib/gettext/po/parser.ex:71

warning: String.lstrip/1 is deprecated. Use String.trim_leading/1 instead
  lib/gettext/po/parser.ex:65

warning: String.strip/1 is deprecated. Use String.trim/1 instead
Found at 2 locations:
  lib/gettext/po/parser.ex:47
  lib/gettext/po/parser.ex:55

warning: String.to_char_list/1 is deprecated. Use String.to_charlist/1 instead
  lib/gettext/po/tokenizer.ex:147

warning: System.stacktrace/0 outside of rescue/catch clauses is deprecated. If you want to support only Elixir v1.7+, you must access __STACKTRACE__ inside a rescue/catch. If you want to support earlier Elixir versions, move System.stacktrace/0 inside a rescue/catch
  lib/plug/conn/wrapper_error.ex:23

warning: transport/3 in Phoenix.Socket is deprecated.

Instead of defining transports in your socket.ex file:

    transport :websocket, Phoenix.Transport.Websocket,
      key1: value1, key2: value2, key3: value3

    transport :longpoll, Phoenix.Transport.LongPoll,
      key1: value1, key2: value2, key3: value3

You should configure websocket/longpoll in your endpoint.ex:

    socket "/socket", MyApp.UserSocket,
      websocket: [key1: value1, key2: value2, key3: value3],
      longpoll: [key1: value1, key2: value2, key3: value3]

Note the websocket/longpoll configuration given to socket/3
will only apply after you remove all transport/3 calls from
your socket definition. If you have explicitly upgraded to
Cowboy 2, any transport defined with the transport/3 macro
will be ignored.
```

there are a list of deprecations here 
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Compatibility%20and%20Deprecations.md

**Comment by yakryder** [comment]
On the surface these issues all look like third-party code: 
- gettext is calling deprecated code
- plug is calling deprecated code
- the [Phoenix socket layer is calling deprecated code](https://github.com/phoenixframework/phoenix_live_reload/issues/75)

In short, unless I'm mistaken in my assessment or have missed a warning coming from the SFN application layer in the output examples, we need changes to the originating third-party libraries and/or dependency updates to fix this. 

@mattwr18 If you are satisfied that my analysis is right, please update the title and description to make clearer the nature of the deviant behavior and/or the work needing to be done. If unsatisfied I'm excited to hear the counterargument!

**Comment by yakryder** [comment]
@75pollet I should also ask since it seems you may have this inflight already -- where are you at so far with this ticket?

**Comment by 75pollet** [comment]
@SherSpock I had trouble reproducing the errors so i haven't done much yet

**Comment by yakryder** [comment]
@75pollet Gotcha

**Comment by mattwr18** [comment]
sorry, I have been silent here about this... I talked to @FedericoEsparza about this, I think this issue could be closed, but I think maybe we were leaving it open to see if anyone else runs into it. 

Thanks for having a look @75pollet  @SherSpock, sorry for any confusion :worried:

**Comment by aonomike** [comment]
We did start from a new slate and generate phoenix 1.4 api only for this repo. I guess this can be closed? @mattwr18 @pollett21

**Comment by yakryder** [comment]
@aonomike Yup this can close
