### ISSUE TITLE
Add Github Pull Request Template

### ISSUE THREAD

**Issue by daumie** [AgileVentures/sing_for_needs#48]
- Pull request templates help guide developers make better software, and a better software development experience. 

- They are obviously extremely useful for open source projects that get many contributions from outsiders, but they can also be very useful for internal projects where all contributors are insiders. 

- They codify and encourage good behavior, thoughtful code, and empathetic interactions with teammates. 

- They normalize and reinforce a workflow regardless of size, scope, or underlying technology used in a project. 

- And they provide consistency and familiarity that makes switching between multiple projects per day a little easier.

**Comment by aonomike** [comment]
I will just copy paste this issue for the sfn-client project 😃
