### ISSUE TITLE
Add Artist `about`Attributes

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sing_for_needs#55]
## Expected Behavior

Add the following attributes to the artist schema
- about
## Current Behavior

There is no about attribute as part of the artist schema
## Possible Solution

 - Add `about:string` attrubute to the Artist schema
 - Update the tests related to the ArtistSchema

Adds an `about` attribute to the Artist which should hold details about the Artist

**Comment by 75pollet** [comment]
Can I work on this? @aonomike
