### ISSUE TITLE
Add Absinthe 

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sing_for_needs#59]
## Expected Behavior

We will be using GraphQL in the repo. There is therefore a need to add Absinthe in the codebase as a dependency
## Current Behavior

The codebase does not have Absinthe, a GraphQL API for elixir
## Possible Solution

Add Absinthe to the deps

**Comment by yakryder** [comment]
@aonomike Where is the discussion on using GraphQL? I see it floated as a possibility in the Slack channel and have not seen any discussion on this repo

**Comment by aonomike** [comment]
@SherSpock maybe I tag this issue as a question? Yes! We had the discussion with @mattwr18 on the elixir mob (we decided to be working on this project henceforth in the elixir mob) and also had it suggested by @FedericoEsparza on slack that we are going to be using graphQL on this project. The motivation of course, was made on the basis to learn that technology among us developers on this project. There could be other reasons based on the nested relationships among schema objects on this project but maybe @mattwr18 has better experience to explain our discussion on the elixir mob.

**Comment by FedericoEsparza** [comment]
Sorry @SherSpock 
It was actually discussed via DM. It wasn't intended as a private decision, however.
Here's our transcript:
<img width="792" alt="Screen Shot 2019-05-08 at 10 46 54 AM" src="https://user-images.githubusercontent.com/11988089/57389066-0b8bb000-717f-11e9-9343-e7f07a30e6f4.png">
