### ISSUE TITLE
Signup/Signin for User

### ISSUE THREAD

**Issue by siddhant3030** [AgileVentures/sing_for_needs#75]
I've created a Model and Schema for User to login. Will start working on controller soon. I've pushed my latest code to feature/login branch.

I've also added following libraries to help us with the login part.
{:comeonin, "~> 4.0"},
{:bcrypt_elixir, "~> 1.0"},
{:guardian, "~> 1.0"}

Also created the Auth folder to keep a track for authentication. Which will later help us during the authorization.  
Please read more about those libraries. Let me know if you find something interesting

**Comment by javpet** [comment]
Duplicate ticket for now, will close this one!
