### ISSUE TITLE
Hosting the application

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sing_for_needs#87]
This is more of an open discussion (and growing with links) rather an issue on where to host the application in the future. Some options gathered:

Heroku
https://hexdocs.pm/phoenix/heroku.html

Google cloud
https://cloud.google.com/community/tutorials/elixir-phoenix-on-google-app-engine

AWS (with docker)
https://thoughtbot.com/blog/deploying-elixir-to-aws-elastic-beanstalk-with-docker

**Comment by aonomike** [comment]
Found something that's free for one instance https://gigalixir.com/#/signup

More [documentation here](https://gigalixir.readthedocs.io/en/latest/)

**Comment by javpet** [comment]
Oh really nice!
