### ISSUE TITLE
Setup Ex Machina

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sing_for_needs#88]
## Expected Behavior

Set up [ex machina](https://github.com/thoughtbot/ex_machina) to be used for generation of test data for unit testing
## Current Behavior

We dont have [Ex Machina](https://github.com/thoughtbot/ex_machina) set up
## Possible Solution

Follow these [instructions](https://github.com/thoughtbot/ex_machina)

**Comment by 3fernandez** [comment]
Hey @aonomike... Have you considered this discussion: https://elixirforum.com/t/are-there-any-alternatives-to-exmachina/6737
