### ISSUE TITLE
Address lodash vulnerability

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sing_for_needs#9]
Address potential security vulnerability
<img width="597" alt="screenshot 2019-02-03 14 03 23" src="https://user-images.githubusercontent.com/11988089/52181895-0a995a00-27ef-11e9-8fc2-b7367af386ba.png">

We can probably deal with this, better, after we upgrade to phx 1.4 and start using webpack, instead of brunch.
 
You can `cd assets && npm audit` to view (If you're running npm 6.1 or higher).
 
**If you spend more than 30 minutes on this, stop and ask for help. It can be a rabbit hole.**

**Comment by yakryder** [comment]
If this is still an issue, it is a component issue of #15

**Comment by FedericoEsparza** [comment]
This was addressed by @75pollet 's #38 PR.
Thank you, Pollet!

I'll close it.
